### ISSUE TITLE
Runs better if I compile it from source

### ISSUE THREAD

**Issue by pizzadude** [flathub/app.xemu.xemu#3]
On a Thinkpad T580 with Intel HD Graphics, this runs better if I compile it from source. THPS2X runs at 20-30FPS on flatpak build, 50-60FPS compiled from source. Could this be due to seccomp sandboxing in flatpak?

**Comment by j8r** [comment]
Got not idea. I have no plan do dig on this for now, any help is welcomed.

**Comment by j8r** [comment]
We can try if `--device=kvm` improves the situation.

**Comment by j8r** [comment]
I haven't noticed any significant performance difference. If you are using Wayland, maybe the flatpak runs through XWayland?

**Comment by j8r** [comment]
Closing, likely an issue with reduced performance using XWayland with Flatpak, not xemu itself.
