### ISSUE TITLE
SDK Update's Mesa Version causes Rendering issues on Steam Deck

### ISSUE THREAD

**Issue by HadetTheUndying** [flathub/app.xemu.xemu#95]
The SDK update has introduced some problems with the SteamDeck. It is probably related to the mesa version included in this SDK the issue was actually introduced in this commit `22ef8df290151bf79a74ef0b4e34a8478f71bf1e`, but I've been trying to track it down thinking it was an xemu issue for well over a month

Issue being tracked in the xemu repo where you can see the problems being introduced
https://github.com/xemu-project/xemu/issues/1279#issuecomment-1374406291

Steps to reproduce
Run any flatpak version after the SDK update referenced above.

Steps to fix currently is to roll back to before the SDK was updated with
`sudo flatpak update --commit=c76629f17bb1516410a1bac1b9e559301141acc63c2d954e5f440c5da0e7b3da app.xemu.xemu`

Suggested fixes. 

1. Roll back the SDK Runtime
2. Use the `mesa-git` runtime (this is actually probably desirable because there is a fix in the latest mesa that improves the performance in a number of games, I recommend opening a PR to do this as opposed to your standard commit method to enable better testing.)

**Comment by j8r** [comment]
We cannot push to `master` directly anyways now 🙂 
Rolling back is definitely not an option.

**Comment by j8r** [comment]
`mesa-git` is in `flathub-beta`, and generally we want to use stable releases for Flatpak.
Mesa-git may solve issues for you, but may have regressions for others too - it goes both ways.

So the proposed work-around for SteamDeck users:
```sh
flatpak remote-add --if-not-exists --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta org.freedesktop.Platform.GL.mesa-git//22.08
FLATPAK_GL_DRIVERS=mesa-git flatpak run app.xemu.xemu
```

**Comment by j8r** [comment]
Depending of your operating system, you may be able to set the `FLATPAK_GL_DRIVERS` environment variable globally. It will of course impact all other flatpaks.

**Comment by HadetTheUndying** [comment]
Uh... So yeah that does not work. 
```(deck@steamdeck launchers)$ FLATPAK_GL_DRIVERS=mesa-git flatpak run app.xemu.xemu
xemu_version: 0.7.70
xemu_branch: 080022833db0896b8af4482e726200acd51507a0
xemu_commit: 080022833db0896b8af4482e726200acd51507a0
xemu_date: Wed Oct  5 12:43:12 AM UTC 2022
xemu_settings_get_base_path: base path: /home/deck/.var/app/app.xemu.xemu/data/xemu/xemu/
xemu_settings_get_path: config path: /home/deck/.var/app/app.xemu.xemu/data/xemu/xemu/xemu.toml
Failed to create main window
```

**Comment by HadetTheUndying** [comment]
@mborgerson suggest we might want to look at what Dolphin is doing here. 

https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/master/org.DolphinEmu.dolphin-emu.yml

Do you want me to open a PR for this tomorrow or are you willing to give it a shot?  I have most of next week to attempt testing to resolve the issue at least that's how it seems right now.

**Comment by HadetTheUndying** [comment]
This appears to be an upstream `mesa` problem with radeonsi. I'm going to leave the issue open for now, but this is not a problem we can fix without rolling the SDK back, which you already said is not feasible and that's fair. I will open an Issue with the mesa bug tracker in the morning. Thanks for responding.

**Comment by j8r** [comment]
@HadetTheUndying what do you mean by

> we might want to look at what Dolphin is doing here.
> https://github.com/flathub/org.DolphinEmu.dolphin-emu/blob/master/org.DolphinEmu.dolphin-emu.yml

You can also build xemu locally, then you'll have the latest version.

**Comment by HadetTheUndying** [comment]
Still present in the flatpak and now manually build binaries. Leads me to believe it's an upstream mesa issue. I just don't know what could be causing it and figuring out which mesa commit broke things is gonna be a nightmare.

```
CPU:          AMD Custom APU 0405
OS Platform:  Linux
OS Version:   Freedesktop.org SDK 22.08 (Flatpak runtime)
Manufacturer: AMD
GPU Model:    AMD Custom GPU 0405 (vangogh, LLVM 14.0.6, DRM 3.45, 5.13.0-valve36-1-neptune)
Driver:       4.6 (Core Profile) Mesa 22.3.2 (git-a09d5e2747)
Shader:       4.60
```

**Comment by HadetTheUndying** [comment]
I'm gonna go ahead and close this because it's not an issue with the flatpak. It's an upstream `mesa` issue for sure. I apologize for the confusion, it was just really inconsistent to test at first. I will start bisecting the mesa changes then open an issue there over the next week. I think some other members of the xemu Discord are also wanting to look into it.
